apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  labels:
    app: python-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: bobcrutchley/python-http-server
        ports:
        - name: http-port
          containerPort: 9000
